{{ range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace:  {{ required "namespace must be defined" $.Values.namespace }}
  labels:
      {{- include "workspace.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range .keys }}
  {{ .key }}:{{ .value | | b64enc }}
  {{ end }}
type: Opaque
{{ end }}